name = Max Content for Multiproject Interaction
description = Maximize the content area for a multiproject page
preview = preview.png
template = maxcontent_multiproject-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/maxcontent_multiproject/maxcontent_multiproject.layout.css
