<?php
/**
 * @file
 * --------------------------------------------------------------------------------------
 * Created by Frank Font (mrfont@room4me.com)
 *
 * Copyright (c) 2015-2018 Room4me.com Software LLC, a Maryland USA company (room4me.com)
 * 
 * All rights reserved.  Contact author for more information.
 * This is BETA software.  No warranty or fitness for use is implied at this time.
 * --------------------------------------------------------------------------------------
 *
 */

namespace bigfathom_autofill;

/**
 * This class is for database schema content
 *
 * @author Frank Font
 */
class DemoData
{
    public function load()
    {
        try
        {

            //TODO
            
        } catch (\Exception $ex) {
            throw $ex;
        }
    }    
}
    