name = Max Content for Multiproject Top Menu Interaction
description = Maximize the content area for a bftopmenu page
preview = preview.png
template = bftopmenu_multiproject-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/bftopmenu_multiproject/bftopmenu_multiproject.layout.css
