<?php
/**
 * @file
 * ------------------------------------------------------------------------------------
 * Created by Frank Font (mrfont@room4me.com)
 *
 * Copyright 2015 Room4me.com Software LLC, a Maryland USA company (room4me.com)
 * ------------------------------------------------------------------------------------
 *
 */

require_once 'core/config.php';


/** 
 * Implements hook_help. 
 */
function bigfathom_forecast_help($path, $arg) 
{
    $contributemsg = 'Contact us at <a href="http://room4me.com/">Room4me.com Software LLC</a> to ask about consulting services.';
    switch ($path)
    {
      case "admin/help#bigfathom_forecast":
          return '<p>'. t("This module has the forecasting logic of the application.") .'</p>'
                .'<p>'.t($contributemsg).'</p>';
          break;
    }
}

/** 
 * Returns information about this module
 */
function bigfathom_forecast_info() 
{
    $info = array();
    $info['version'] = BIGFATHOM_FORECAST_VERSION_INFO;
    return $info;
}


function bigfathom_forecast_menu() 
{
    $items = array();

    return $items;
}





