<?php
/**
 * @file
 * --------------------------------------------------------------------------------------
 * Created by Frank Font (mrfont@room4me.com)
 *
 * Copyright (c) 2015-2018 Room4me.com Software LLC, a Maryland USA company (room4me.com)
 * 
 * All rights reserved.  Contact author for more information.
 * This is BETA software.  No warranty or fitness for use is implied at this time.
 * --------------------------------------------------------------------------------------
 *
 */

require_once 'core/config.php';
module_load_include('php','bigfathom_template_library','core/Context');
module_load_include('inc','bigfathom_template_library','functions/menus');

/** 
 * Implements hook_help. 
 */
function bigfathom_template_library_help($path, $arg) 
{
    $contributemsg = 'Contact at <a href="http://room4me.com/">Room4me.com Software LLC</a> to ask about consulting services.';
    switch ($path)
    {
      case "admin/help#bigfathom_template_library":
          return '<p>'. t("This module has the template management elements of the application.") .'</p>'
                .'<p>'.t($contributemsg).'</p>';
          break;
    }
}

/** 
 * Returns information about this module
 */
function bigfathom_template_library_info() 
{
    $info = array();
    $info['version'] = BIGFATHOM_TEMPLATE_LIBRARY_VERSION_INFO;
    return $info;
}

function bigfathom_template_library_menu_access($myargs)
{
    if(isset($myargs['selected_templateid']))
    {
        $result = ($myargs['selected_templateid'] != NULL);
    } else {
        $result = FALSE;
    }
    return $result;
}

function bigfathom_template_library_get_menu_page_arguments($curpath=NULL)
{

    if($curpath == NULL)
    {
        $curpath = current_path();
    }
    $onemenuitems = menu_get_item($curpath);
    $pageargs = $onemenuitems['page_arguments'];
    
    return $pageargs;
}

function bigfathom_template_library_menu() 
{
    $items = array();
    
    bigfathom_template_library_menu_core_callbacks($items);
    
    return $items;
}


//About application
function bigfathom_template_library_viewabout_form() 
{
    return drupal_get_form('bigfathom_template_library_viewabout_form_builder');
}

function bigfathom_template_library_viewabout_form_builder($form, &$form_state)
{
    try
    {
        $oPI = new \bigfathom_template_library\ViewAboutPage();
        $form = array();
        $disabled = TRUE;
        $myvalues = array();    //No values for this one.
        return $oPI->getForm($form, $form_state, $disabled, $myvalues);
    } catch (\Exception $ex) {
        throw $ex;
    }
}

