name = Max Page Content Area with Squeezed Top
description = Maximize the content area with minimal top area
preview = preview.png
template = maxcontent_squeezetop-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/maxcontent/maxcontent_squeezetop.layout.css
